export type CatalogLevel = "region" | "unit" | "parcel";
export type GeometryType = "点" | "线" | "面" | "注记";

export type CatalogItem = {
  id: string;
  name: string;
  geometry: GeometryType;
  group: string;
  content: string;
  transmission: string;
};

export type StrategyItem = {
  id: string;
  name: string;
  condition: string;
  expression: string;
  requirement: string;
};

export const elementCatalog: Record<CatalogLevel, CatalogItem[]> = {
  region: [
    {
      id: "R-01",
      name: "片区范围",
      geometry: "面",
      group: "基础范围",
      content: "片区城市设计编制和成果适用范围",
      transmission: "确定相关单元及跨单元对象的整体范围",
    },
    {
      id: "R-02",
      name: "核心",
      geometry: "面",
      group: "特色空间结构",
      content: "片区核心范围、主导功能和总体目标",
      transmission: "由单元核心、中心或重点地块承接细化",
    },
    {
      id: "R-03",
      name: "轴线",
      geometry: "线",
      group: "特色空间结构",
      content: "片区主要空间轴线中心线",
      transmission: "单元轴线填写来源片区对象编号",
    },
    {
      id: "R-04",
      name: "轴线影响范围",
      geometry: "面",
      group: "特色空间结构",
      content: "轴线两侧需要统筹的影响范围",
      transmission: "单元细化界面、节点和开放空间要求",
    },
    {
      id: "R-05",
      name: "中心",
      geometry: "点",
      group: "特色空间结构",
      content: "片区级中心和重要门户中心点位",
      transmission: "单元中心填写来源片区对象编号",
    },
    {
      id: "R-06",
      name: "中心范围",
      geometry: "面",
      group: "特色空间结构",
      content: "中心的功能和空间影响范围",
      transmission: "单元细化公共空间和高度体量秩序",
    },
    {
      id: "R-07",
      name: "生态绿楔",
      geometry: "面",
      group: "开放空间体系",
      content: "进入城镇空间的生态绿楔范围",
      transmission: "单元落实生态边界和建设限制",
    },
    {
      id: "R-08",
      name: "城市绿环中心线",
      geometry: "线",
      group: "开放空间体系",
      content: "城市绿环总体线位和连续关系",
      transmission: "单元绿环中心线承接并细化",
    },
    {
      id: "R-09",
      name: "城市绿环控制范围",
      geometry: "面",
      group: "开放空间体系",
      content: "绿环宽度和空间控制范围",
      transmission: "单元落实有效宽度和断点修复",
    },
    {
      id: "R-10",
      name: "生态廊道中心线",
      geometry: "线",
      group: "开放空间体系",
      content: "生态廊道走向及连接关系",
      transmission: "单元廊道中心线承接并细化",
    },
    {
      id: "R-11",
      name: "生态廊道控制范围",
      geometry: "面",
      group: "开放空间体系",
      content: "生态廊道边界、缓冲和建设限制范围",
      transmission: "单元落实边界、宽度和接口",
    },
    {
      id: "R-12",
      name: "公共空间节点",
      geometry: "点",
      group: "开放空间体系",
      content: "片区级公共空间和重要活动节点",
      transmission: "单元公共空间节点承接并深化",
    },
    {
      id: "R-13",
      name: "公共空间范围",
      geometry: "面",
      group: "开放空间体系",
      content: "重要公共空间节点的影响或服务范围",
      transmission: "单元落实开放空间边界和联系",
    },
    {
      id: "R-14",
      name: "风貌分区",
      geometry: "面",
      group: "风貌与色彩",
      content: "片区风貌类型和总体形象分区",
      transmission: "单元细化建筑形态和重点界面",
    },
    {
      id: "R-15",
      name: "色彩分区",
      geometry: "面",
      group: "风貌与色彩",
      content: "片区色彩总体秩序和适用范围",
      transmission: "单元明确色卡和建筑适用要求",
    },
    {
      id: "R-16",
      name: "眺望点",
      geometry: "点",
      group: "景观眺望系统",
      content: "重要观察点及观察高程",
      transmission: "单元校准点位和观察高程",
    },
    {
      id: "R-17",
      name: "景观标志点",
      geometry: "点",
      group: "景观眺望系统",
      content: "重要被观赏对象或地标",
      transmission: "单元保持景观对象和识别关系",
    },
    {
      id: "R-18",
      name: "视线通廊中心线",
      geometry: "线",
      group: "景观眺望系统",
      content: "眺望点至景观对象的视线中心线",
      transmission: "单元细化视线和天际线控制",
    },
    {
      id: "R-19",
      name: "视线通廊控制范围",
      geometry: "面",
      group: "景观眺望系统",
      content: "视廊或视域的空间控制范围",
      transmission: "单元落实高度和遮挡控制",
    },
    {
      id: "R-20",
      name: "重点控制区候选范围",
      geometry: "面",
      group: "城市设计控制区",
      content: "片区层面识别的重点控制候选范围",
      transmission: "单元确认边界、级别和唯一重点类型后转为现行管控",
    },
  ],
  unit: [
    {
      id: "U-01",
      name: "单元范围",
      geometry: "面",
      group: "基础范围",
      content: "单元详细规划编制范围",
      transmission: "作为单元对象和控制分区完整性检查边界",
    },
    {
      id: "U-02",
      name: "核心",
      geometry: "面",
      group: "特色空间结构",
      content: "单元核心范围、功能和公共空间组织",
      transmission: "地块落实功能、高度、体量和开放空间",
    },
    {
      id: "U-03",
      name: "轴线",
      geometry: "线",
      group: "特色空间结构",
      content: "单元轴线中心线、起讫节点和连续关系",
      transmission: "地块落实建筑控制线、界面和节点",
    },
    {
      id: "U-04",
      name: "轴线影响范围",
      geometry: "面",
      group: "特色空间结构",
      content: "轴线两侧空间影响和重点管控范围",
      transmission: "地块落实高点、体量、开放空间和慢行接口",
    },
    {
      id: "U-05",
      name: "中心",
      geometry: "点",
      group: "特色空间结构",
      content: "单元中心点位、级别和主导功能",
      transmission: "地块落实功能复合和公共空间节点",
    },
    {
      id: "U-06",
      name: "中心范围",
      geometry: "面",
      group: "特色空间结构",
      content: "中心服务和空间影响范围",
      transmission: "地块落实首层开放和高度秩序",
    },
    {
      id: "U-07",
      name: "生态绿楔",
      geometry: "面",
      group: "开放空间体系",
      content: "生态绿楔边界和建设限制范围",
      transmission: "地块落实生态边界、退让和连续绿化",
    },
    {
      id: "U-08",
      name: "城市绿环中心线",
      geometry: "线",
      group: "开放空间体系",
      content: "城市绿环线位和慢行联系",
      transmission: "地块落实城市绿道和接口",
    },
    {
      id: "U-09",
      name: "城市绿环控制范围",
      geometry: "面",
      group: "开放空间体系",
      content: "城市绿环宽度和控制范围",
      transmission: "地块落实有效宽度和开放空间",
    },
    {
      id: "U-10",
      name: "生态廊道中心线",
      geometry: "线",
      group: "开放空间体系",
      content: "生态廊道走向和连接关系",
      transmission: "地块落实蓝绿连续和通行联系",
    },
    {
      id: "U-11",
      name: "生态廊道控制范围",
      geometry: "面",
      group: "开放空间体系",
      content: "生态廊道、缓冲和建设限制范围",
      transmission: "地块落实退让、缓冲和公共可达",
    },
    {
      id: "U-12",
      name: "公共空间节点",
      geometry: "点",
      group: "开放空间体系",
      content: "公共空间节点位置和功能",
      transmission: "地块落实节点、出入口和连接通道",
    },
    {
      id: "U-13",
      name: "公共空间范围",
      geometry: "面",
      group: "开放空间体系",
      content: "公共空间节点边界或服务范围",
      transmission: "地块落实面积、界面和开放要求",
    },
    {
      id: "U-14",
      name: "风貌分区",
      geometry: "面",
      group: "风貌与色彩",
      content: "风貌类型、建筑形态和重点界面要求",
      transmission: "地块落实屋顶、立面、材质和尺度",
    },
    {
      id: "U-15",
      name: "色彩分区",
      geometry: "面",
      group: "风貌与色彩",
      content: "主色、辅色、点缀色和禁用色范围",
      transmission: "地块落实材料色和重点界面配色",
    },
    {
      id: "U-16",
      name: "眺望点",
      geometry: "点",
      group: "景观眺望系统",
      content: "观察点及观察高程",
      transmission: "地块保留观察条件并开展三维校核",
    },
    {
      id: "U-17",
      name: "景观标志点",
      geometry: "点",
      group: "景观眺望系统",
      content: "景观对象或地标位置",
      transmission: "地块落实景观对象周边控制",
    },
    {
      id: "U-18",
      name: "视线通廊中心线",
      geometry: "线",
      group: "景观眺望系统",
      content: "视线中心线和景观联系",
      transmission: "地块落实视线退让和天际线控制",
    },
    {
      id: "U-19",
      name: "视线通廊控制范围",
      geometry: "面",
      group: "景观眺望系统",
      content: "视廊、视域和遮挡控制范围",
      transmission: "地块落实高度包络和第五立面",
    },
    {
      id: "U-20",
      name: "一般控制区",
      geometry: "面",
      group: "城市设计控制区",
      content: "一般控制区完整范围",
      transmission: "地块采用一般控制区附加图则",
    },
    {
      id: "U-21",
      name: "重点控制区",
      geometry: "面",
      group: "城市设计控制区",
      content: "重点控制区范围、级别和唯一重点类型",
      transmission: "地块采用重点控制区附加图则并落实强化内容",
    },
  ],
  parcel: [
    {
      id: "P-01",
      name: "地块边界",
      geometry: "面",
      group: "基础定位",
      content: "调用现行详细规划地块边界和编号",
      transmission: "作为地块控制对象的定位边界",
    },
    {
      id: "P-02",
      name: "一般控制区",
      geometry: "面",
      group: "控制分区",
      content: "地块内一般控制区范围",
      transmission: "承接单元一般控制区对象",
    },
    {
      id: "P-03",
      name: "重点控制区",
      geometry: "面",
      group: "控制分区",
      content: "地块内重点控制区范围、级别和唯一重点类型",
      transmission: "承接单元重点控制区对象",
    },
    {
      id: "P-04",
      name: "通透率控制界面",
      geometry: "线",
      group: "一般控制区8项",
      content: "计算界面、通透段和控制值",
      transmission: "来源于单元轴线、中心或界面要求",
    },
    {
      id: "P-05",
      name: "墙面绿视率控制界面",
      geometry: "线",
      group: "一般控制区8项",
      content: "围墙或实体界面的绿视率控制对象",
      transmission: "来源于单元开放空间和风貌要求",
    },
    {
      id: "P-06",
      name: "建筑高宽比控制界面",
      geometry: "线",
      group: "一般控制区8项",
      content: "沿街第一排建筑高宽比计算界面",
      transmission: "来源于单元轴线和风貌分区",
    },
    {
      id: "P-07",
      name: "同高率控制范围",
      geometry: "面",
      group: "一般控制区8项",
      content: "成组或连续建筑同高率适用范围",
      transmission: "来源于单元高度和形态秩序",
    },
    {
      id: "P-08",
      name: "街道高宽比控制段",
      geometry: "线",
      group: "一般控制区8项",
      content: "代表性街道高宽比计算区段",
      transmission: "来源于单元轴线和街道空间要求",
    },
    {
      id: "P-09",
      name: "首层开放空间",
      geometry: "面",
      group: "一般控制区8项",
      content: "首层公共开放空间边界和面积",
      transmission: "来源于单元中心、核心或公共空间要求",
    },
    {
      id: "P-10",
      name: "口袋公园",
      geometry: "面",
      group: "一般控制区8项",
      content: "口袋公园边界、面积和出入口",
      transmission: "来源于单元公共空间节点",
    },
    {
      id: "P-11",
      name: "城市绿道",
      geometry: "线",
      group: "一般控制区8项",
      content: "绿道中心线、有效宽度和接口",
      transmission: "来源于单元城市绿环或生态廊道",
    },
    {
      id: "P-12",
      name: "建筑高点",
      geometry: "点",
      group: "强化空间控制",
      content: "重点控制区建筑高点位置和高度",
      transmission: "来源于单元轴线、中心或重点控制区",
    },
    {
      id: "P-13",
      name: "公共空间节点",
      geometry: "点",
      group: "强化空间控制",
      content: "地块公共空间节点位置和功能",
      transmission: "来源于单元公共空间节点",
    },
    {
      id: "P-14",
      name: "出入口",
      geometry: "点",
      group: "强化空间控制",
      content: "公共空间、绿道、枢纽和慢行出入口",
      transmission: "承接单元接口和可达性要求",
    },
    {
      id: "P-15",
      name: "建筑控制线",
      geometry: "线",
      group: "强化空间控制",
      content: "建筑退让和空间界面控制线",
      transmission: "来源于单元轴线、中心和重点控制区",
    },
    {
      id: "P-16",
      name: "连续界面",
      geometry: "线",
      group: "强化空间控制",
      content: "连续沿街或滨水界面控制段",
      transmission: "来源于单元风貌、轴线和滨水要求",
    },
    {
      id: "P-17",
      name: "历史街巷",
      geometry: "线",
      group: "历史风貌区",
      content: "历史街巷线位和保护控制",
      transmission: "来源于历史风貌区",
    },
    {
      id: "P-18",
      name: "岸线界面",
      geometry: "线",
      group: "滨水和川塬区",
      content: "滨水岸线及公共空间界面",
      transmission: "来源于重要滨水和川塬区",
    },
    {
      id: "P-19",
      name: "天际线控制线",
      geometry: "线",
      group: "景观眺望系统",
      content: "重要视点或界面的天际线控制",
      transmission: "来源于单元景观眺望系统",
    },
    {
      id: "P-20",
      name: "慢行联系",
      geometry: "线",
      group: "强化空间控制",
      content: "地块内部及相邻地块慢行联系",
      transmission: "来源于单元绿环、公共空间和枢纽要求",
    },
    {
      id: "P-21",
      name: "建筑体量控制范围",
      geometry: "面",
      group: "强化空间控制",
      content: "建筑体量、高度和组合控制范围",
      transmission: "来源于单元核心、中心和重点控制区",
    },
    {
      id: "P-22",
      name: "开放空间",
      geometry: "面",
      group: "开放空间",
      content: "公共开放空间边界和管理范围",
      transmission: "来源于单元开放空间体系",
    },
    {
      id: "P-23",
      name: "视线通廊控制范围",
      geometry: "面",
      group: "景观眺望系统",
      content: "视线退让、限高和遮挡控制范围",
      transmission: "来源于单元视线通廊控制范围",
    },
    {
      id: "P-24",
      name: "历史风貌保护范围",
      geometry: "面",
      group: "历史风貌区",
      content: "保护、保留、恢复和协调控制范围",
      transmission: "来源于历史风貌区",
    },
    {
      id: "P-25",
      name: "滨水公共空间",
      geometry: "面",
      group: "滨水和川塬区",
      content: "滨水开放空间和公共可达范围",
      transmission: "来源于重要滨水和川塬区",
    },
    {
      id: "P-26",
      name: "生态连续空间",
      geometry: "面",
      group: "生态空间",
      content: "生态缓冲、连续绿化和建设限制范围",
      transmission: "来源于单元生态绿楔或生态廊道",
    },
    {
      id: "P-27",
      name: "站城一体化空间",
      geometry: "面",
      group: "城市枢纽区",
      content: "枢纽集散、换乘和站城融合范围",
      transmission: "来源于城市枢纽区",
    },
    {
      id: "P-28",
      name: "活力界面",
      geometry: "线",
      group: "重要发展区",
      content: "首层功能和沿街活力界面",
      transmission: "来源于重要发展区或单元中心",
    },
    {
      id: "P-29",
      name: "分期建设控制范围",
      geometry: "面",
      group: "重要发展区",
      content: "首期实施和后续衔接控制范围",
      transmission: "来源于重要发展区",
    },
  ],
};

export const transmissionStrategies: StrategyItem[] = [
  {
    id: "T-01",
    name: "直接继承",
    condition: "上位要求已达到本级成果深度",
    expression: "保持对象、控制值和控制性质",
    requirement: "记录来源成果、来源对象和直接继承结果",
  },
  {
    id: "T-02",
    name: "完整继承",
    condition: "上位对象完整落入一个下位单元",
    expression: "建立一个下位对象",
    requirement: "填写来源对象编号，几何与属性保持完整",
  },
  {
    id: "T-03",
    name: "分割继承",
    condition: "轴线、廊道、绿环或视廊跨越多个单元",
    expression: "按单元边界建立多个下位对象",
    requirement: "使用统一接口编号，分割后能够还原完整对象",
  },
  {
    id: "T-04",
    name: "深化细化",
    condition: "上位对象位置明确但深度不足",
    expression: "补充边界、属性、节点、界面或量化要求",
    requirement: "不得降低上位刚性要求",
  },
  {
    id: "T-05",
    name: "空间分解",
    condition: "总体系统需落实为多个点、线、面对象",
    expression: "拆分形成标准几何要素类",
    requirement: "关联成组对象编号并保持系统关系",
  },
  {
    id: "T-06",
    name: "组合转换",
    condition: "多个来源对象共同形成一个下位对象",
    expression: "确定主要来源并记录其他来源",
    requirement: "不得把多个编号拼接在同一字段",
  },
  {
    id: "T-07",
    name: "规则转译",
    condition: "单元空间对象需要生成地块管控要求",
    expression: "空间叠加—规则触发—要求生成",
    requirement: "记录规则、来源单元对象、地块和要求编号",
  },
  {
    id: "T-08",
    name: "补充新增",
    condition: "本级识别出上位未明确的新对象",
    expression: "建立本级新增对象",
    requirement: "记录识别依据、控制性质和向下传导方式",
  },
  {
    id: "T-09",
    name: "不予转化",
    condition: "研究内容不具备现行管控条件",
    expression: "保留研究状态，不进入现行成果库",
    requirement: "记录处置原因和数据状态",
  },
  {
    id: "T-10",
    name: "不适用",
    condition: "标准要素或规则对目标单元、地块不适用",
    expression: "保留标准图层或规则项并标注不适用",
    requirement: "不得删除标准图层或用空白数据替代说明",
  },
];

export const generalControlStrategies: StrategyItem[] = [
  {
    id: "G-01",
    name: "通透率",
    condition: "按沿街界面和地块功能判定",
    expression: "沿街界面分段、通透段和指标注记",
    requirement: "标注计算界面、界面总长度、通透段、控制值、计算式和例外条件",
  },
  {
    id: "G-02",
    name: "墙面绿视率",
    condition: "设置围墙或实体界面时判定",
    expression: "围墙界面、可见绿化和指标注记",
    requirement: "标注计算范围、可见绿化对象、控制值和例外依据",
  },
  {
    id: "G-03",
    name: "建筑高宽比",
    condition: "沿街第一排建筑适用",
    expression: "控制对象、建筑高度和连续面宽",
    requirement: "标注建筑高度、连续面宽、塔楼组合、适用道路和计算方法",
  },
  {
    id: "G-04",
    name: "同高率",
    condition: "存在成组或连续建筑时判定",
    expression: "建筑组合、相同高度对象和比例注记",
    requirement: "标注相同高度建筑数量、基底面积比例、相邻高差和接口条件",
  },
  {
    id: "G-05",
    name: "街道高宽比",
    condition: "代表性街道断面适用",
    expression: "道路断面、建筑高度、退界和比值",
    requirement: "标注道路宽度、建筑高度、退界、计算式、允许范围和处理方式",
  },
  {
    id: "G-06",
    name: "首层开放空间",
    condition: "承担公共活动和步行联系时判定",
    expression: "闭合控制面、出入口和开放注记",
    requirement: "标注位置、边界、面积、进深、净高、开放时段、管理属性和连续关系",
  },
  {
    id: "G-07",
    name: "口袋公园",
    condition: "适用性判定要求设置时表达",
    expression: "闭合控制面、设施和出入口",
    requirement: "标注面积或比例、最小宽度、沿街位置、出入口和公共属性",
  },
  {
    id: "G-08",
    name: "城市绿道",
    condition: "单元绿环、廊道或绿道传导至地块时表达",
    expression: "中心线、控制范围、出入口和接口编号",
    requirement: "标注有效宽度、连续性、出入口和相邻地块接口",
  },
];

export const keyControlStrategies: StrategyItem[] = [
  {
    id: "K-10",
    name: "城市轴线区",
    condition: "唯一重点类型代码 10",
    expression: "高点、控制线、连续界面、开放空间和轴线接口",
    requirement: "强化高点建筑、建筑体量、建筑控制线、沿街界面、公共空间、视线和慢行联系",
  },
  {
    id: "K-20",
    name: "历史风貌区",
    condition: "唯一重点类型代码 20",
    expression: "保护、保留、恢复、整治和新建协调对象及正负面要求",
    requirement: "强化历史格局、历史街巷、城市记忆建筑、高度体量、屋顶、立面、材质和色彩",
  },
  {
    id: "K-30",
    name: "重要滨水和川塬区",
    condition: "唯一重点类型代码 30",
    expression: "滨水平面、典型横剖面、连续公共空间和岸线接口",
    requirement: "强化滨水开放、全季节滨水空间、岸线界面、天际线、生态连续和公共可达",
  },
  {
    id: "K-40",
    name: "城市枢纽区",
    condition: "唯一重点类型代码 40",
    expression: "交通与公共空间一体化、出入口、慢行联系、高点和体量关系",
    requirement: "强化站城关系、集散空间、出入口、慢行换乘、门户形象、高点和开发秩序",
  },
  {
    id: "K-50",
    name: "重要发展区",
    condition: "唯一重点类型代码 50",
    expression: "整体空间框架、首期实施内容和后续地块接口",
    requirement: "强化功能结构、高点体量、开放空间、活力界面、慢行系统和分期建设衔接",
  },
];

