/**
 * Land-use palette extracted from F:\\20260710.lyr.
 * ArcGIS renderer: UniqueValueRenderer, field `ydyhflmc`, 110 classes.
 */

export const LAND_USE_PALETTE = {
  residential: "#FFFF2D",
  commercial: "#FF0000",
  administration: "#FF00FF",
  culture: "#FF7F00",
  education: "#FF85C9",
  sports: "#00A57C",
  healthcare: "#FF7F7E",
  welfare: "#FF9F7F",
  research: "#E6005C",
  industry: "#BB9674",
  logistics: "#8761D3",
  road: "#A3A3A3",
  highway: "#ADADAD",
  transport: "#B7B7B7",
  utility: "#006380",
  park: "#00FF00",
  protectionGreen: "#148D4A",
  square: "#ACFFCF",
  special: "#859156",
  water: "#338EC0",
  blank: "#FFFFFF",
  unknown: "#D9DDDA",
} as const;

export const LAND_USE_LEGEND = [
  { label: "住宅", color: LAND_USE_PALETTE.residential },
  { label: "商业商务", color: LAND_USE_PALETTE.commercial },
  { label: "机关团体", color: LAND_USE_PALETTE.administration },
  { label: "文化", color: LAND_USE_PALETTE.culture },
  { label: "教育", color: LAND_USE_PALETTE.education },
  { label: "科研", color: LAND_USE_PALETTE.research },
  { label: "体育", color: LAND_USE_PALETTE.sports },
  { label: "医疗卫生", color: LAND_USE_PALETTE.healthcare },
  { label: "社会福利", color: LAND_USE_PALETTE.welfare },
  { label: "工业", color: LAND_USE_PALETTE.industry },
  { label: "仓储物流", color: LAND_USE_PALETTE.logistics },
  { label: "道路交通", color: LAND_USE_PALETTE.road },
  { label: "交通场站", color: LAND_USE_PALETTE.transport },
  { label: "公用设施", color: LAND_USE_PALETTE.utility },
  { label: "公园绿地", color: LAND_USE_PALETTE.park },
  { label: "防护绿地", color: LAND_USE_PALETTE.protectionGreen },
  { label: "广场", color: LAND_USE_PALETTE.square },
  { label: "特殊用地", color: LAND_USE_PALETTE.special },
  { label: "水域", color: LAND_USE_PALETTE.water },
] as const;

const EXACT_NAME_COLORS: Record<string, string> = {
  一类工业用地: LAND_USE_PALETTE.industry,
  工业用地: LAND_USE_PALETTE.industry,
  新型产业用地: LAND_USE_PALETTE.industry,
  一类物流仓储用地: LAND_USE_PALETTE.logistics,
  物流仓储用地: LAND_USE_PALETTE.logistics,
  二类城镇住宅用地: LAND_USE_PALETTE.residential,
  城镇住宅用地: LAND_USE_PALETTE.residential,
  商业用地: LAND_USE_PALETTE.commercial,
  商务金融用地: LAND_USE_PALETTE.commercial,
  娱乐用地: LAND_USE_PALETTE.commercial,
  机关团体用地: LAND_USE_PALETTE.administration,
  文化活动用地: LAND_USE_PALETTE.culture,
  图书与展览用地: LAND_USE_PALETTE.culture,
  科研用地: LAND_USE_PALETTE.research,
  中小学用地: LAND_USE_PALETTE.education,
  中等职业教育用地: LAND_USE_PALETTE.education,
  高等教育用地: LAND_USE_PALETTE.education,
  高等职业教育用地: LAND_USE_PALETTE.education,
  幼儿园用地: LAND_USE_PALETTE.education,
  其他教育用地: LAND_USE_PALETTE.education,
  体育场馆用地: LAND_USE_PALETTE.sports,
  体育训练用地: LAND_USE_PALETTE.sports,
  医院用地: LAND_USE_PALETTE.healthcare,
  基层医疗卫生设施用地: LAND_USE_PALETTE.healthcare,
  老年人社会福利用地: LAND_USE_PALETTE.welfare,
  儿童社会福利用地: LAND_USE_PALETTE.welfare,
  铁路用地: LAND_USE_PALETTE.transport,
  城市轨道交通用地: LAND_USE_PALETTE.transport,
  公共交通场站用地: LAND_USE_PALETTE.transport,
  对外交通场站用地: LAND_USE_PALETTE.transport,
  社会停车场用地: LAND_USE_PALETTE.transport,
  其他交通设施用地: LAND_USE_PALETTE.transport,
  公路用地: LAND_USE_PALETTE.highway,
  城镇道路用地: LAND_USE_PALETTE.road,
  城镇村道路用地: LAND_USE_PALETTE.road,
  供水用地: LAND_USE_PALETTE.utility,
  排水用地: LAND_USE_PALETTE.utility,
  供电用地: LAND_USE_PALETTE.utility,
  供燃气用地: LAND_USE_PALETTE.utility,
  供热用地: LAND_USE_PALETTE.utility,
  通信用地: LAND_USE_PALETTE.utility,
  消防用地: LAND_USE_PALETTE.utility,
  环卫用地: LAND_USE_PALETTE.utility,
  公用设施营业网点用地: LAND_USE_PALETTE.commercial,
  公园绿地: LAND_USE_PALETTE.park,
  防护绿地: LAND_USE_PALETTE.protectionGreen,
  广场用地: LAND_USE_PALETTE.square,
  河流水面: LAND_USE_PALETTE.water,
  使领馆用地: LAND_USE_PALETTE.special,
  文物古迹用地: LAND_USE_PALETTE.special,
  宗教用地: LAND_USE_PALETTE.special,
  殡葬用地: LAND_USE_PALETTE.special,
  教育科研设计功能区: LAND_USE_PALETTE.research,
  商业办公功能区: LAND_USE_PALETTE.commercial,
  "文化活动用地+商业用地混合用地": LAND_USE_PALETTE.culture,
  "基层医疗卫生设施用地+老年人社会福利用地": LAND_USE_PALETTE.healthcare,
  "工业用地+商务金融用地": LAND_USE_PALETTE.industry,
  "商业用地+商务金融用地": LAND_USE_PALETTE.commercial,
  "商务金融用地+商业用地": LAND_USE_PALETTE.commercial,
  商务金融用地混合商业用地: LAND_USE_PALETTE.commercial,
  "公共交通场站用地+二类城镇住宅用地": LAND_USE_PALETTE.transport,
  "公共交通场站用地+公园绿地": LAND_USE_PALETTE.transport,
  "公园绿地+社会停车场用地": LAND_USE_PALETTE.park,
};

const CODE_PREFIX_COLORS: Array<[string, string]> = [
  ["0701", LAND_USE_PALETTE.residential],
  ["0801", LAND_USE_PALETTE.administration],
  ["0802", LAND_USE_PALETTE.research],
  ["0803", LAND_USE_PALETTE.culture],
  ["0804", LAND_USE_PALETTE.education],
  ["0805", LAND_USE_PALETTE.sports],
  ["0806", LAND_USE_PALETTE.healthcare],
  ["0807", LAND_USE_PALETTE.welfare],
  ["0901", LAND_USE_PALETTE.commercial],
  ["0902", LAND_USE_PALETTE.commercial],
  ["0903", LAND_USE_PALETTE.commercial],
  ["1001", LAND_USE_PALETTE.industry],
  ["1101", LAND_USE_PALETTE.logistics],
  ["1202", LAND_USE_PALETTE.highway],
  ["1207", LAND_USE_PALETTE.road],
  ["1201", LAND_USE_PALETTE.transport],
  ["1206", LAND_USE_PALETTE.transport],
  ["1208", LAND_USE_PALETTE.transport],
  ["1209", LAND_USE_PALETTE.transport],
  ["13", LAND_USE_PALETTE.utility],
  ["1401", LAND_USE_PALETTE.park],
  ["1402", LAND_USE_PALETTE.protectionGreen],
  ["1403", LAND_USE_PALETTE.square],
  ["15", LAND_USE_PALETTE.special],
  ["1701", LAND_USE_PALETTE.water],
];

export function landUseColor(code: string, name: string) {
  const normalizedName = name.trim();
  const exactColor = EXACT_NAME_COLORS[normalizedName];
  if (exactColor) return exactColor;

  const primaryCode = code.trim().split("+")[0];
  return CODE_PREFIX_COLORS.find(([prefix]) => primaryCode.startsWith(prefix))?.[1]
    ?? LAND_USE_PALETTE.unknown;
}
